INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Assign', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:sap2010="http://schemas.microsoft.com/netfx/2010/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List Capacity="1" x:TypeArguments="x:Object"><p:Assign VirtualizedContainerService.HintSize="484,60" x:Name="__ReferenceID0"><p:Assign.To><p:OutArgument x:TypeArguments="x:Int32"></p:OutArgument></p:Assign.To><p:Assign.Value><p:InArgument x:TypeArguments="x:Int32"></p:InArgument></p:Assign.Value></p:Assign></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List Capacity="4" x:TypeArguments="x:Object"><scg:List Capacity="4" x:TypeArguments="x:Object"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Delay', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><p:Delay x:Name="__ReferenceID0" VirtualizedContainerService.HintSize="438,22" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Flowchart', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><p:Flowchart x:Name="__ReferenceID0" VirtualizedContainerService.HintSize="438,51"><WorkflowViewStateService.ViewState><scg:Dictionary x:TypeArguments="x:String, x:Object"><x:Boolean x:Key="IsExpanded">False</x:Boolean></scg:Dictionary></WorkflowViewStateService.ViewState><p:Flowchart.StartNode><x:Null /></p:Flowchart.StartNode></p:Flowchart></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'If', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><p:If x:Name="__ReferenceID0" VirtualizedContainerService.HintSize="484,270"><p:If.Then><p:Sequence VirtualizedContainerService.HintSize="242,83"><WorkflowViewStateService.ViewState><scg:Dictionary x:TypeArguments="x:String, x:Object"><x:Boolean x:Key="IsExpanded">True</x:Boolean></scg:Dictionary></WorkflowViewStateService.ViewState></p:Sequence></p:If.Then><p:If.Else><p:Sequence VirtualizedContainerService.HintSize="242,83"><WorkflowViewStateService.ViewState><scg:Dictionary x:TypeArguments="x:String, x:Object"><x:Boolean x:Key="IsExpanded">True</x:Boolean></scg:Dictionary></WorkflowViewStateService.ViewState></p:Sequence></p:If.Else></p:If></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Invoke Method', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><p:InvokeMethod MethodName="{x:Null}" x:Name="__ReferenceID0" DisplayName="Invoke Method" VirtualizedContainerService.HintSize="484,134" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Rethrow', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><p:Rethrow x:Name="__ReferenceID0" VirtualizedContainerService.HintSize="438,22" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Sequence', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><p:Sequence x:Name="__ReferenceID0" VirtualizedContainerService.HintSize="438,83"><WorkflowViewStateService.ViewState><scg:Dictionary x:TypeArguments="x:String, x:Object"><x:Boolean x:Key="IsExpanded">True</x:Boolean></scg:Dictionary></WorkflowViewStateService.ViewState></p:Sequence></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Throw', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><p:Throw x:Name="__ReferenceID0" VirtualizedContainerService.HintSize="438,22" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Try Catch', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><p:TryCatch x:Name="__ReferenceID0" DisplayName="Try Catch" VirtualizedContainerService.HintSize="438,265" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Add Data Row', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:AddDataRow ArrayRow="{x:Null}" DataRow="{x:Null}" DataTable="{x:Null}" x:Name="__ReferenceID0" DisplayName="Add Data Row" VirtualizedContainerService.HintSize="438,185" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Break', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:Break x:Name="__ReferenceID0" VirtualizedContainerService.HintSize="438,22" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Attach Browser', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:BrowserScope Browser="{x:Null}" BrowserType="{x:Null}" SearchScope="{x:Null}" Selector="{x:Null}" TimeoutMS="{x:Null}" UiBrowser="{x:Null}" x:Name="__ReferenceID0" DisplayName="Attach Browser" VirtualizedContainerService.HintSize="438,191"><ui:BrowserScope.Body><p:ActivityAction x:TypeArguments="x:Object"><p:ActivityAction.Argument><p:DelegateInArgument x:TypeArguments="x:Object" Name="ContextTarget" /></p:ActivityAction.Argument><p:Sequence DisplayName="Do" VirtualizedContainerService.HintSize="200,83"><WorkflowViewStateService.ViewState><scg:Dictionary x:TypeArguments="x:String, x:Object"><x:Boolean x:Key="IsExpanded">True</x:Boolean></scg:Dictionary></WorkflowViewStateService.ViewState></p:Sequence></p:ActivityAction></ui:BrowserScope.Body></ui:BrowserScope></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Build Data Table', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:BuildDataTable DataTable="{x:Null}" x:Name="__ReferenceID0" DisplayName="Build Data Table" VirtualizedContainerService.HintSize="370,59" TableInfo="&lt;NewDataSet&gt;&#xD;&#xA;  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;&#xD;&#xA;    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;TableName&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;&#xD;&#xA;      &lt;xs:complexType&gt;&#xD;&#xA;        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;&#xD;&#xA;          &lt;xs:element name=&quot;TableName&quot;&gt;&#xD;&#xA;            &lt;xs:complexType&gt;&#xD;&#xA;              &lt;xs:sequence&gt;&#xD;&#xA;                &lt;xs:element name=&quot;Column1&quot; minOccurs=&quot;0&quot;&gt;&#xD;&#xA;                  &lt;xs:simpleType&gt;&#xD;&#xA;                    &lt;xs:restriction base=&quot;xs:string&quot;&gt;&#xD;&#xA;                      &lt;xs:maxLength value=&quot;100&quot; /&gt;&#xD;&#xA;                    &lt;/xs:restriction&gt;&#xD;&#xA;                  &lt;/xs:simpleType&gt;&#xD;&#xA;                &lt;/xs:element&gt;&#xD;&#xA;                &lt;xs:element name=&quot;Column2&quot; type=&quot;xs:int&quot; minOccurs=&quot;0&quot; /&gt;&#xD;&#xA;              &lt;/xs:sequence&gt;&#xD;&#xA;            &lt;/xs:complexType&gt;&#xD;&#xA;          &lt;/xs:element&gt;&#xD;&#xA;        &lt;/xs:choice&gt;&#xD;&#xA;      &lt;/xs:complexType&gt;&#xD;&#xA;    &lt;/xs:element&gt;&#xD;&#xA;  &lt;/xs:schema&gt;&#xD;&#xA;  &lt;TableName&gt;&#xD;&#xA;    &lt;Column1&gt;text&lt;/Column1&gt;&#xD;&#xA;    &lt;Column2&gt;1&lt;/Column2&gt;&#xD;&#xA;  &lt;/TableName&gt;&#xD;&#xA;&lt;/NewDataSet&gt;" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Click', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:Click AlterIfDisabled="{x:Null}" DelayBefore="{x:Null}" DelayMS="{x:Null}" SendWindowMessages="{x:Null}" SimulateClick="{x:Null}" x:Name="__ReferenceID0" ClickType="CLICK_SINGLE" VirtualizedContainerService.HintSize="438,68" KeyModifiers="None" MouseButton="BTN_LEFT"><ui:Click.CursorPosition><ui:CursorPosition Position="Center"><ui:CursorPosition.OffsetX><p:InArgument x:TypeArguments="x:Int32" /></ui:CursorPosition.OffsetX><ui:CursorPosition.OffsetY><p:InArgument x:TypeArguments="x:Int32" /></ui:CursorPosition.OffsetY></ui:CursorPosition></ui:Click.CursorPosition><ui:Click.Target><ui:Target ClippingRegion="{x:Null}" Element="{x:Null}" Selector="{x:Null}" Id="ce09d125-a092-4945-8f25-371b54174a38"><ui:Target.TimeoutMS><p:InArgument x:TypeArguments="x:Int32" /></ui:Target.TimeoutMS><ui:Target.WaitForReady><p:InArgument x:TypeArguments="ui:WaitForReady" /></ui:Target.WaitForReady></ui:Target></ui:Click.Target></ui:Click></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Continue', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:Continue x:Name="__ReferenceID0" VirtualizedContainerService.HintSize="438,22" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Find Children', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:FindChildren Children="{x:Null}" Filter="{x:Null}" x:Name="__ReferenceID0" DisplayName="Find Children" VirtualizedContainerService.HintSize="438,68" Scope="FIND_CHILDREN"><ui:FindChildren.Target><ui:Target ClippingRegion="{x:Null}" Element="{x:Null}" Selector="{x:Null}" Id="f9064f9d-4b34-41a8-98c6-2a93a6e99289"><ui:Target.TimeoutMS><p:InArgument x:TypeArguments="x:Int32" /></ui:Target.TimeoutMS><ui:Target.WaitForReady><p:InArgument x:TypeArguments="ui:WaitForReady" /></ui:Target.WaitForReady></ui:Target></ui:FindChildren.Target></ui:FindChildren></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Find Element', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:sap2010="http://schemas.microsoft.com/netfx/2010/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:WaitUiElementAppear FoundElement="{x:Null}" WaitActive="{x:Null}" WaitVisible="{x:Null}" x:Name="__ReferenceID0" DisplayName="Find Element" VirtualizedContainerService.HintSize="438,68"><ui:WaitUiElementAppear.Target><ui:Target ClippingRegion="{x:Null}" Element="{x:Null}" Selector="{x:Null}" Id="a59fde13-b637-4b3d-9811-f7766ef32215"><ui:Target.TimeoutMS><p:InArgument x:TypeArguments="x:Int32" /></ui:Target.TimeoutMS><ui:Target.WaitForReady><p:InArgument x:TypeArguments="ui:WaitForReady" /></ui:Target.WaitForReady></ui:Target></ui:WaitUiElementAppear.Target></ui:WaitUiElementAppear></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'For Each', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:ForEach x:TypeArguments="x:Object" CurrentIndex="{x:Null}" x:Name="__ReferenceID0" DisplayName="For Each" VirtualizedContainerService.HintSize="438,207"><ui:ForEach.Body><p:ActivityAction x:TypeArguments="x:Object"><p:ActivityAction.Argument><p:DelegateInArgument x:TypeArguments="x:Object" Name="item" /></p:ActivityAction.Argument><p:Sequence DisplayName="Body" VirtualizedContainerService.HintSize="200,83"><WorkflowViewStateService.ViewState><scg:Dictionary x:TypeArguments="x:String, x:Object"><x:Boolean x:Key="IsExpanded">True</x:Boolean></scg:Dictionary></WorkflowViewStateService.ViewState></p:Sequence></p:ActivityAction></ui:ForEach.Body></ui:ForEach></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Get Credential',
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:sap2010="http://schemas.microsoft.com/netfx/2010/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:GetRobotCredential AssetName="{x:Null}" Password="{x:Null}" TimeoutMS="{x:Null}" Username="{x:Null}" x:Name="__ReferenceID0" CacheStrategy="None" DisplayName="Get Credential" VirtualizedContainerService.HintSize="334,180" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Get Text', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:GetValue ContinueOnError="{x:Null}" Value="{x:Null}" x:Name="__ReferenceID0" DisplayName="Get Text" VirtualizedContainerService.HintSize="438,68"><ui:GetValue.Target><ui:Target ClippingRegion="{x:Null}" Element="{x:Null}" Selector="{x:Null}" Id="6d75606b-b60f-448a-9ada-b71669d6871f"><ui:Target.TimeoutMS><p:InArgument x:TypeArguments="x:Int32" /></ui:Target.TimeoutMS><ui:Target.WaitForReady><p:InArgument x:TypeArguments="ui:WaitForReady" /></ui:Target.WaitForReady></ui:Target></ui:GetValue.Target></ui:GetValue></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Do While', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:InterruptibleDoWhile x:Name="__ReferenceID0" DisplayName="Do While" VirtualizedContainerService.HintSize="438,248"><ui:InterruptibleDoWhile.Body><p:Sequence DisplayName="Body" VirtualizedContainerService.HintSize="200,83"><WorkflowViewStateService.ViewState><scg:Dictionary x:TypeArguments="x:String, x:Object"><x:Boolean x:Key="IsExpanded">True</x:Boolean></scg:Dictionary></WorkflowViewStateService.ViewState></p:Sequence></ui:InterruptibleDoWhile.Body></ui:InterruptibleDoWhile></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'While', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:InterruptibleWhile x:Name="__ReferenceID0" DisplayName="While" VirtualizedContainerService.HintSize="438,248"><ui:InterruptibleWhile.Body><p:Sequence DisplayName="Body" VirtualizedContainerService.HintSize="200,83"><WorkflowViewStateService.ViewState><scg:Dictionary x:TypeArguments="x:String, x:Object"><x:Boolean x:Key="IsExpanded">True</x:Boolean></scg:Dictionary></WorkflowViewStateService.ViewState></p:Sequence></ui:InterruptibleWhile.Body></ui:InterruptibleWhile></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Invoke Workflow File', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:sap2010="http://schemas.microsoft.com/netfx/2010/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:InvokeWorkflowFile ArgumentsVariable="{x:Null}" ContinueOnError="{x:Null}" WorkflowFileName="{x:Null}" x:Name="__ReferenceID0" DisplayName="Invoke Workflow File" VirtualizedContainerService.HintSize="438,112" UnSafe="False"><ui:InvokeWorkflowFile.Arguments><scg:Dictionary x:TypeArguments="x:String, p:Argument" /></ui:InvokeWorkflowFile.Arguments></ui:InvokeWorkflowFile></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Log Message', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:LogMessage Message="{x:Null}" x:Name="__ReferenceID0" DisplayName="Log Message" VirtualizedContainerService.HintSize="438,91" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Message Box', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:MessageBox Caption="{x:Null}" ChosenButton="{x:Null}" x:Name="__ReferenceID0" AutoCloseAfter="00:00:00" DisplayName="Message Box" VirtualizedContainerService.HintSize="438,84" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Multiple Assign', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:MultipleAssign x:Name="__ReferenceID0" DisplayName="Multiple Assign" VirtualizedContainerService.HintSize="438,100"><ui:MultipleAssign.AssignOperations><scg:List x:TypeArguments="ui:AssignOperation" Capacity="4"><ui:AssignOperation To="{x:Null}" Value="{x:Null}" /></scg:List></ui:MultipleAssign.AssignOperations></ui:MultipleAssign></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Navigate To', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:NavigateTo Browser="{x:Null}" Url="{x:Null}" x:Name="__ReferenceID0" DisplayName="Navigate To" VirtualizedContainerService.HintSize="438,59" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Open Browser', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:OpenBrowser AutomaticallyDownloadWebDriver="{x:Null}" BrowserType="{x:Null}" CommunicationMethod="{x:Null}" Hidden="{x:Null}" NewSession="{x:Null}" Private="{x:Null}" UiBrowser="{x:Null}" Url="{x:Null}" x:Name="__ReferenceID0" DisplayName="Open Browser" VirtualizedContainerService.HintSize="467,184"><ui:OpenBrowser.Body><p:ActivityAction x:TypeArguments="x:Object"><p:ActivityAction.Argument><p:DelegateInArgument x:TypeArguments="x:Object" Name="ContextTarget" /></p:ActivityAction.Argument><p:Sequence DisplayName="Do" VirtualizedContainerService.HintSize="200,83"><WorkflowViewStateService.ViewState><scg:Dictionary x:TypeArguments="x:String, x:Object"><x:Boolean x:Key="IsExpanded">True</x:Boolean></scg:Dictionary></WorkflowViewStateService.ViewState></p:Sequence></p:ActivityAction></ui:OpenBrowser.Body></ui:OpenBrowser></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Retry Scope', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:RetryScope x:Name="__ReferenceID0" DisplayName="Retry Scope" VirtualizedContainerService.HintSize="438,257"><ui:RetryScope.ActivityBody><p:ActivityAction><p:Sequence DisplayName="Action" VirtualizedContainerService.HintSize="200,83"><WorkflowViewStateService.ViewState><scg:Dictionary x:TypeArguments="x:String, x:Object"><x:Boolean x:Key="IsExpanded">True</x:Boolean></scg:Dictionary></WorkflowViewStateService.ViewState></p:Sequence></p:ActivityAction></ui:RetryScope.ActivityBody><ui:RetryScope.Condition><p:ActivityFunc x:TypeArguments="x:Boolean" /></ui:RetryScope.Condition></ui:RetryScope></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Select Item', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:SelectItem AlterIfDisabled="{x:Null}" ContinueOnError="{x:Null}" DelayAfter="{x:Null}" DelayBefore="{x:Null}" Item="{x:Null}" Items="{x:Null}" x:Name="__ReferenceID0" DisplayName="Select Item" VirtualizedContainerService.HintSize="438,96"><ui:SelectItem.Target><ui:Target ClippingRegion="{x:Null}" Element="{x:Null}" Selector="{x:Null}" Id="b648e58c-9900-47ba-b0bf-accc18848aaf"><ui:Target.TimeoutMS><p:InArgument x:TypeArguments="x:Int32" /></ui:Target.TimeoutMS><ui:Target.WaitForReady><p:InArgument x:TypeArguments="ui:WaitForReady" /></ui:Target.WaitForReady></ui:Target></ui:SelectItem.Target></ui:SelectItem></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Send Hotkey', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:sap2010="http://schemas.microsoft.com/netfx/2010/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:SendHotkey ClickBeforeTyping="{x:Null}" DelayBefore="{x:Null}" DelayBetweenKeys="{x:Null}" DelayMS="{x:Null}" EmptyField="{x:Null}" Key="{x:Null}" SendWindowMessages="{x:Null}" SpecialKey="{x:Null}" x:Name="__ReferenceID0" Activate="True" DisplayName="Send Hotkey" VirtualizedContainerService.HintSize="438,114" KeyModifiers="None"><ui:SendHotkey.Target><ui:Target ClippingRegion="{x:Null}" Element="{x:Null}" Selector="{x:Null}" Id="2726cf73-b75b-4d7b-ac7d-6428d51da63f"><ui:Target.TimeoutMS><p:InArgument x:TypeArguments="x:Int32" /></ui:Target.TimeoutMS><ui:Target.WaitForReady><p:InArgument x:TypeArguments="ui:WaitForReady" /></ui:Target.WaitForReady></ui:Target></ui:SendHotkey.Target></ui:SendHotkey></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Start Process', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:sap2010="http://schemas.microsoft.com/netfx/2010/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:StartProcess Arguments="{x:Null}" FileName="{x:Null}" WorkingDirectory="{x:Null}" x:Name="__ReferenceID0" DisplayName="Start Process" VirtualizedContainerService.HintSize="438,87" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Type Into', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:TypeInto AlterIfDisabled="{x:Null}" ClickBeforeTyping="{x:Null}" DelayBefore="{x:Null}" DelayBetweenKeys="{x:Null}" DelayMS="{x:Null}" EmptyField="{x:Null}" SendWindowMessages="{x:Null}" SimulateType="{x:Null}" Text="{x:Null}" x:Name="__ReferenceID0" Activate="True" DisplayName="Type Into" VirtualizedContainerService.HintSize="438,96"><ui:TypeInto.Target><ui:Target ClippingRegion="{x:Null}" Element="{x:Null}" Selector="{x:Null}" Id="1b892ed4-7b93-48d2-b99a-9bc5e4dd3b3c"><ui:Target.TimeoutMS><p:InArgument x:TypeArguments="x:Int32" /></ui:Target.TimeoutMS><ui:Target.WaitForReady><p:InArgument x:TypeArguments="ui:WaitForReady" /></ui:Target.WaitForReady></ui:Target></ui:TypeInto.Target></ui:TypeInto></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Element Exists', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:UiElementExists Exists="{x:Null}" x:Name="__ReferenceID0" DisplayName="Element Exists" VirtualizedContainerService.HintSize="438,68"><ui:UiElementExists.Target><ui:Target ClippingRegion="{x:Null}" Element="{x:Null}" Selector="{x:Null}" Id="d48c5890-8431-4146-b803-9966973e0f24"><ui:Target.TimeoutMS><p:InArgument x:TypeArguments="x:Int32" /></ui:Target.TimeoutMS><ui:Target.WaitForReady><p:InArgument x:TypeArguments="ui:WaitForReady" /></ui:Target.WaitForReady></ui:Target></ui:UiElementExists.Target></ui:UiElementExists></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Attach Window', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:p="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:WindowScope ApplicationWindow="{x:Null}" SearchScope="{x:Null}" Selector="{x:Null}" TimeoutMS="{x:Null}" Window="{x:Null}" x:Name="__ReferenceID0" DisplayName="Attach Window" VirtualizedContainerService.HintSize="438,191"><ui:WindowScope.Body><p:ActivityAction x:TypeArguments="x:Object"><p:ActivityAction.Argument><p:DelegateInArgument x:TypeArguments="x:Object" Name="ContextTarget" /></p:ActivityAction.Argument><p:Sequence DisplayName="Do" VirtualizedContainerService.HintSize="200,83"><WorkflowViewStateService.ViewState><scg:Dictionary x:TypeArguments="x:String, x:Object"><x:Boolean x:Key="IsExpanded">True</x:Boolean></scg:Dictionary></WorkflowViewStateService.ViewState></p:Sequence></p:ActivityAction></ui:WindowScope.Body></ui:WindowScope></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Read Range', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:ReadRange DataTable="{x:Null}" WorkbookPath="{x:Null}" x:Name="__ReferenceID0" AddHeaders="True" DisplayName="Read Range" VirtualizedContainerService.HintSize="438,87" Range="A1:A2" SheetName="Sheet1" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Deserialize Json', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:njl="clr-namespace:Newtonsoft.Json.Linq;assembly=Newtonsoft.Json" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:DeserializeJson x:TypeArguments="njl:JObject" JsonObject="{x:Null}" JsonString="{x:Null}" x:Name="__ReferenceID0" DisplayName="Deserialize JSON" VirtualizedContainerService.HintSize="438,59" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );INSERT INTO
  SpeechRecognitionActivity (version, name, xml)
VALUES
  ('2022.4.3_Classic', 'Deserialize Json Array', 
   '<ClipboardData Version="1.0" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation" xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib" xmlns:ui="http://schemas.uipath.com/workflow/activities" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><ClipboardData.Data><scg:List x:TypeArguments="x:Object" Capacity="1"><ui:DeserializeJsonArray JsonArray="{x:Null}" JsonString="{x:Null}" x:Name="__ReferenceID0" DisplayName="Deserialize JSON Array" VirtualizedContainerService.HintSize="438,59" /></scg:List></ClipboardData.Data><ClipboardData.Metadata><scg:List x:TypeArguments="x:Object" Capacity="4"><scg:List x:TypeArguments="x:Object" Capacity="4"><x:Reference>__ReferenceID0</x:Reference></scg:List></scg:List></ClipboardData.Metadata></ClipboardData>'
  );